### ISSUE TITLE
Screen share doesn't work properly

### ISSUE THREAD

**Issue by rafailmdzdv** [YaLTeR/niri#1500]
Hi! I have a problem with screen sharing in Telegram and cannot share screen from browser (Zen, it just freezes and browser crushes).
There is windows display problem in Telegram. They load not properly. But screencast works without any problem from OBS. Thank you!

[config](https://github.com/rafailmdzdv/dotfiles/blob/master/.config/niri/config.kdl)

[img](https://postimg.cc/gallery/3Jv7m7m)

### System Information

* niri version: niri 25.02 (v25.02-121-gc359d248)

* Distro: Gentoo Base System release 2.17

* GPU: NVIDIA GeForce GTX1650

* CPU: Intel(R) Xeon(R) E5-2680 v3 (24) @ 3.30 GHz

**Comment by rafailmdzdv** [comment]
Forgot to write. There is no problem when I share only one window (browser, for example) from Telegram. This problem only with entire screen.

[mp4](https://drive.google.com/file/d/15yNl6ja7ujiD4aNIYTiNSJoNMnXUcSA6/view?usp=sharing)

**Comment by YaLTeR** [comment]
> NVIDIA

Hello, set this flag, it should fix it: https://github.com/YaLTeR/niri/wiki/Configuration:-Debug-Options#wait-for-frame-completion-in-pipewire

**Comment by rafailmdzdv** [comment]
Hello! Yes, It works. Now telegram shows screen properly, thank you! But screen sharing from Zen still doesn't work :(. I have xdg-desktop-portal-gnome and wireplumber that work. I checked `media.peerconnection.enable` and `media.webrtc.capture.allow-pipewire` parameters in `about:config` and all of them set to true

**Comment by YaLTeR** [comment]
They broke it on the zen side by disabling dmabuf screencast for some reason. I believe there's some flag in about:options that brings it back

**Comment by rafailmdzdv** [comment]
You are right. Set `widget.dmabuf.force-enabled` to `true`, and it works now! Thank you for help and for great wm :)
