### ISSUE TITLE
Zed Editor is broken in Niri

### ISSUE THREAD

**Issue by cetra3** [YaLTeR/niri#2335]
This may not be a niri bug specifically, but the zed editor is broken in niri.  The reason is that when the application starts up, something invalidates the vulkan surface, and you have to resize the window to get it to work again.

Maybe there is something with the way that niri starts up windows that it's skipping a resize check or something.

### System Information

* niri version: niri 25.08 (01be0e6)

* Distro: Arch

* GPU: Nvidia 3090

* CPU: AMD Ryzen 9 3900XT

**Comment by YaLTeR** [comment]
idk if related but niri requests the target window size right away, which is different from other compositors. I've seen some clients have bugs where they did not expect this. This is not a niri bug

**Comment by rempas** [comment]
> idk if related but niri requests the target window size right away, which is different from other compositors. I've seen some clients have bugs where they did not expect this. This is not a niri bug

In that case, could it be possible that Niri has an option to not ask it for certain apps (using window rules), in order to allow those clients to properly work?

**Comment by YaLTeR** [comment]
There is one: https://github.com/YaLTeR/niri/blob/c69464c1288789020d9a086f86c970a7dc49b8c7/resources/default-config.kdl#L311-L319

**Comment by cetra3** [comment]
>idk if related but niri requests the target window size right away, which is different from other compositors. I've seen some clients have bugs where they did not expect this. This is not a niri bug

gnome *also* requests the window size straight away in the method `create_surface_configured`: https://github.com/kvark/blade/blob/da2eb085a9f5761c9ee96df6fd8ad7a03e3b4fb2/blade-graphics/src/lib.rs#L151-L153


I have attached logs of running gnome and niri using the [blade particles example](https://github.com/kvark/blade/tree/main/examples/particle) which freezes up on niri and is fine on gnome (I've added a few extra debug logs to troubleshoot).

[niri.log](https://github.com/user-attachments/files/22199333/niri.log)
[gnome.log](https://github.com/user-attachments/files/22199334/gnome.log)

There is one difference, at the start of the niri log I get a debug log saying:

```
pci id for fd 16: 10de:2204, driver (null)
pci id for fd 17: 10de:2204, driver (null)
```

Which happens when this line of code is called: https://github.com/kvark/blade/blob/da2eb085a9f5761c9ee96df6fd8ad7a03e3b4fb2/blade-graphics/src/vulkan/init.rs#L335

**Comment by TheK0tYaRa** [comment]
Zed 0.200.5 (537f6781a9dd6d453a3e132e10528982fd299cb5) from flatpak doesn't seem to have this issue when running on niri 25.08 (01be0e6)

**Comment by b0o** [comment]
This happens not only with zed but with any gpui application, you can reproduce with one of the examples from the gpui crate. 

> Zed 0.200.5 (537f6781a9dd6d453a3e132e10528982fd299cb5) from flatpak doesn't seem to have this issue when running on niri 25.08 ([01be0e6](https://github.com/YaLTeR/niri/commit/01be0e65f4eb91a9cd624ac0b76aaeab765c7294))

@TheK0tYaRa Is it possible the flatpak version is running with xwayland on your machine? I’ve verified the issue does not happen when running zed via xwayland.

**Comment by TheK0tYaRa** [comment]
> [@TheK0tYaRa](https://github.com/TheK0tYaRa) Is it possible the flatpak version is running with xwayland on your machine? 

nope, `xwininfo` doesn't pick it up.

**Comment by genius-alray** [comment]
Reproduce on Arch Linux, Niri 25.08, Zed 0.208.3, RTX 3060Ti (with `nvidia-open-dkms` 580.95)

And I saw tons of `[blade_graphics::hal::surface] Acquire failed because the surface is out of date` in Zed.log, before resizing the window.

Everything works well after resizing the window manually.

**Comment by davinpkn** [comment]
Any workarounds?

**Comment by griccardos** [comment]
> Any workarounds?

Two workarounds I have used:
- resizing the window with a shortcut immediately after launch - not ideal but takes a second once, and works thereafter
- running it under X11 by running with `WAYLAND_DISPLAY='' zeditor`. you can create a `.desktop` file and put that there if you use a launch manager. make sure xwayland satellite is installed and running in niri.

**Comment by davinpkn** [comment]
> > Any workarounds?
> 
> Two workarounds I have used:
> 
> * resizing the window with a shortcut immediately after launch - not ideal but takes a second once, and works thereafter
> * running it under X11 by running with `WAYLAND_DISPLAY='' zeditor`. you can create a `.desktop` file and put that there if you use a launch manager. make sure xwayland satellite is installed and running in niri.

ty!!

**Comment by pcarrier** [comment]
Reproduced on NixOS with latest Zed (0.208.5), latest niri (both 25.08 and main). Only happens with nvidia drivers AFAICT (can reproduce reliably with niri+nvidia, cannot reproduce with niri+intel or niri+nouveau). Can confirm a single window resize unblocks it for me. No problems with cosmic in tiling mode or not.

**Comment by TheK0tYaRa** [comment]
So the average state of nvidia closed-source drivers, huh?

**Comment by CodeMonkeyX** [comment]
> So the average state of nvidia closed-source drivers, huh?

Just an FYI I am running the CachyOS open drivers and having this same behavior on a 4070ti.

**Comment by CodedNil** [comment]
Can confirm this applies to any GPUI app I've tried including zlaunch, but also I believe most if not all ICED apps, definitely ashell and the few cosmic apps I tried.
I've also experienced this while working on my own app which doesn't use any UI framework, just winit and wgpu, haven't been able to figure out anything specific for the cause but as others have said resizing it fixes.

**Comment by YaLTeR** [comment]
fwiw on both my AMD systems I don't have any problems running Zed

**Comment by Philipp-M** [comment]
Yeah it's likely *yet another nvidia bug*.
I could reproduce the same issue with the Xilem examples, but *not* with bevy examples, which is interesting, because both are using wgpu/winit as backend (as well as likely all the other examples listed here).

I couldn't reproduce it on an intel gpu.

**Comment by CodedNil** [comment]
I'm using the latest nvidia drivers atm, but I didn't used to get this bug until a few months ago. I changed back to driver version 535 and that works, presumably broke somewhere around 560 or 570 idk. Beta 590 is broken still too.
No idea what can be done on your end if anything to fix this, but maybe this extra info is good.

**Comment by devzeth** [comment]
Might fix this, open pr: https://github.com/zed-industries/zed/pull/45153

**Comment by probably-neb** [comment]
zed-industries/zed#45153 is my attempt to fix issues with the settings window, however, I have no idea if it does for sure, as I was unable to reproduce it myself. FWIW. Would love for some people who are experiencing issues to let me know in the PR comments or https://github.com/zed-industries/zed/issues/40361 if it fixes it for them, or causes more issues. Please @-mention me directly if you do leave a comment!

**Comment by 0PandaDEV** [comment]
Just tested it with the new fix from @probably-neb and https://github.com/vleerapp/vleer/commit/9bb418688071f5a5a7f6bcc8a2c1572e3e4ea9ce, but It's still the same behavior.

WM: Niri
GPU: RTX 3060
Driver: nvidia-open-dkms 580.119.02-1
OS: Arch Linux

https://github.com/user-attachments/assets/ade5d35c-254c-41e3-abc1-c77a7c536cdc

**Comment by machinacanis** [comment]
reproduced on Fedora 43 (the kernel is Linux 6.17.11), niri version 25.08, zed version 0.214.7

my gpu is rtx3080, with nvidia driver

I found so many `[blade_graphics::hal::surface] Acquire failed because the surface is out of date` in the logs, like:

```plaintext
2025-12-19T17:20:39+08:00 WARN  [blade_graphics::hal::surface] Acquire failed because the surface is out of date
2025-12-19T17:20:39+08:00 WARN  [blade_graphics::hal::surface] Acquire failed because the surface is out of date
2025-12-19T17:20:39+08:00 WARN  [blade_graphics::hal::surface] Acquire failed because the surface is out of date
2025-12-19T17:20:39+08:00 WARN  [blade_graphics::hal::surface] Acquire failed because the surface is out of date
2025-12-19T17:20:39+08:00 WARN  [blade_graphics::hal::surface] Acquire failed because the surface is out of date
2025-12-19T17:20:39+08:00 ERROR [crates/gpui/src/window.rs:1126] window not found
2025-12-19T17:20:39+08:00 ERROR [crates/gpui/src/window.rs:1138] window not found
```

**Comment by Philipp-M** [comment]
FWIW: This is the diff in Xilem/Masonry that did fix the issue for me: https://github.com/linebender/xilem/pull/1550 So it might help in zed too?

**Comment by camspiers** [comment]
Adding all the zed issues tracking this here so they are all linked together, though please note @YaLTeR I think that this is caused by these various apps not handling the vulkan outdated swapchain error correctly. For example see:

https://github.com/linebender/xilem/pull/1550

and:

https://github.com/iced-rs/iced/pull/3067

Issues:

https://github.com/zed-industries/zed/issues/40481
https://github.com/zed-industries/zed/issues/44814
https://github.com/zed-industries/zed/issues/39097
https://github.com/zed-industries/zed/issues/45836

@YaLTeR However, given a lot of people are running into this with Niri but not all other WMs it would be good to understand why Niri triggers the outdated swapchain from Vulkan but other WMs don't when opening the same application.

See docs for Vulkan here:

https://docs.vulkan.org/tutorial/latest/03_Drawing_a_triangle/04_Swap_chain_recreation.html#_suboptimal_or_out_of_date_swap_chain

And an example of how this is surfaced in wgpu and how wgpu specifically encourages you to handle it here:

https://sotrh.github.io/learn-wgpu/beginner/tutorial2-surface/#render

**Comment by YaLTeR** [comment]
Could you try niri-git? Smithay had some fixes that could be relevant, but not sure if they apply in this case.

**Comment by camspiers** [comment]
@YaLTeR I just tried niri-git, and I can confirm that the problem with zed still persists.

niri 25.11 (v25.11-46-gcf0b4bc0)

**Comment by camspiers** [comment]
Note that even in vkcube, the canonical vulkan test app, it wasn't until the following commit landed that in Niri the cube wouldn't spin, or wouldn't launch (I can't remember which).

https://github.com/krh/vkcube/pull/57/files

So if you want a minimal repro app, you can checkout an earlier commit.

**Comment by YaLTeR** [comment]
I see. Well as I mentioned zed runs fine for me, so prob for someone who can reproduce to debug this

**Comment by cetra3** [comment]
I can repro easily, but not sure the best setup to debug. If there are any guides I can have a look at or any documentation to get me started

**Comment by cetra3** [comment]
@YaLTeR I've managed to get a minimal repro on my machine, but not sure what the next steps are.  I have compiled from `main` with some minimal changes around log files, but otherwise have left things as is (here's a diff of my changes: [niri-log-changes-diff.txt](https://github.com/user-attachments/files/24399476/niri-log-changes-diff.txt)

I've created a config with `spawn-at-startup` loading the [particles demo](https://github.com/kvark/blade/tree/main/examples/particle) and nothing else.   Then I start niri in another tty, and confirm it's frozen, then I cmd + right click to trigger a "resize" to unfreeze it & confirm it works.

Here's a copy of the logs in totality of a session: [niri.log](https://github.com/user-attachments/files/24399479/niri.log)

What is interesting is in the logs is when it's broken, I can see `send_pending_configure` is hit, but the `Serial` struct doesn't match the number when it hits `commit`.

I.e, I see this log first which has `Serial(4)`:

```
2026-01-01T06:18:19.873055Z DEBUG send_pending_configure: niri::window::mapped: src/window/mapped.rs:1011: sending configure serial=Serial(4) surface=ObjectId(wl_surface@27)
```

But in the `commit` log, I see `Serial(2)`:

```
2026-01-01T06:18:19.873122Z DEBUG commit: niri::handlers::compositor: src/handlers/compositor.rs:60: commit surface=wl_surface@27
2026-01-01T06:18:19.873146Z DEBUG commit:on_commit: niri::window::mapped: src/window/mapped.rs:1301: on_commit surface=wl_surface@27 surface=ObjectId(wl_surface@27) serial=Serial(2)
```

Another interesting thing is that for that surface, there are not `commit` logs until after it's unfrozen.  Could it be some weird accounting within smithay around acknowledged serials?

As soon as I cmd + right click to unfreeze it, I see the serial numbers match up, and then it continuously calls `commit`:

I.e, there is now a commit with `Serial(2018)` in both log entries
```
2026-01-01T06:18:33.060593Z DEBUG send_pending_configure: niri::window::mapped: src/window/mapped.rs:1011: sending configure serial=Serial(2018) surface=ObjectId(wl_surface@27)
2026-01-01T06:18:33.064081Z DEBUG commit: niri::handlers::compositor: src/handlers/compositor.rs:60: commit surface=wl_surface@27
2026-01-01T06:18:33.064158Z DEBUG commit:on_commit: niri::window::mapped: src/window/mapped.rs:1301: on_commit surface=wl_surface@27 surface=ObjectId(wl_surface@27) serial=Serial(2018)
```

**Comment by cetra3** [comment]
Just an update: The bug happens in the [`anvil`](https://github.com/Smithay/smithay/tree/master/anvil) test compositor as well, so I think this is a bug in [Smithay](https://github.com/Smithay/smithay), I will continue investigations there

**Comment by virtuallyunknown** [comment]
There is a launcher called [zlaunch](https://github.com/zortax/zlaunch) and it seems it might be affected by the same problem. The launcher just opens in a "frozen" state and can't be interacted with. There are some workaround here like having a `window-rule`, but that can't be applied here since it's not a window but a layer.

```
 ❯ sleep 5 && niri msg layers 
Output "DP-2":
  Background layer:
    Surface:
      Namespace: "wallpaper"
      Keyboard interactivity: none

  Bottom layer: (empty)

  Top layer:
    Surface:
      Namespace: "waybar"
      Keyboard interactivity: none

  Overlay layer:
    Surface:
      Namespace: "zlaunch"
      Keyboard interactivity: exclusive
```

It also can't be resized because, well, it's a launcher. My knowledge on the whole topic is very limited but I thought I'd report my findings here if that's useful. Zed also seems broken for me unless the window gets resized.

- niri 25.11 (v25.11-1-g311ca6b5)
- nvidia-open 590.48.01-4
- zlaunch-bin 0.3.0-1
- zed 0.218.6+stable

I opened [an issue](https://github.com/zortax/zlaunch/issues/15) on the zlaunch repo, and one person mentioned that both of these programs appear to be using blade-graphics library.

**Comment by camspiers** [comment]
@virtuallyunknown I've identified the exact issue in the blade library here: https://github.com/zed-industries/zed/issues/40481#issuecomment-3688093740

**Comment by virtuallyunknown** [comment]
> [@virtuallyunknown](https://github.com/virtuallyunknown) I've identified the exact issue in the blade library here: [zed-industries/zed#40481 (comment)](https://github.com/zed-industries/zed/issues/40481#issuecomment-3688093740)

Cheers mate, I also saw your comment in the other repo. Unfortunately, I can't be of much help here, other than providing logs or other info if requested, as my knowledge is limited. Will keep an eye on this thread and the other.

**Comment by rafftoubol** [comment]
Hi all, previously zeditor worked then it stopped opening one day - I realised it was because nvidia-smi stopped being able to communicate with the nvidia-open associated kernel module, it seems I didn't notice till I tried to open zed because all other processes were falling back onto my igpu. After reinstalling nvidia-open zed started working.

Tldr: try reinstalling nvidia-open if your zeditor breaks one day and you stumble on this thread looking for a fix (on niri).

**Comment by icedman** [comment]
I coded a temporary workaround for this annoying bug. (quick enough with AI)

https://github.com/icedman/notes/blob/master/niri_scripts/windows.py

It simply resizes zed windows width-1 and restore width+1 after it is opened.

zshrc:

```sh
alias zed=windows.py & zed
```

When zed is opened from command line  script will be called. If zed has an option for a startup script it would be better.

**Comment by argosnothing** [comment]
> I coded a temporary workaround for this annoying bug. (quick enough with AI)
> 
> https://github.com/icedman/notes/blob/master/niri_scripts/windows.py
> 
> It simply resizes zed windows width-1 and restore width+1 after it is opened.
> 
> zshrc:
> 
> ```
> alias zed=windows.py & zed
> ```
> 
> When zed is opened from command line script will be called. If zed has an option for a startup script it would be better.

This also occurs when opening up zed windows spawned through the editor, like settings popup

**Comment by icedman** [comment]
There is an ipc subscribe. If that works perhaps the hack would be less intrusive.

**Comment by icedman** [comment]
> https://github.com/icedman/notes/blob/master/niri_scripts/windows.py

Updated to run as a daemon. Resizes zed and its popups whenever they are created.

https://github.com/icedman/notes/blob/master/niri_scripts/windows_spy.py

**Comment by WERDXZ** [comment]
https://github.com/zed-industries/zed/issues/37556

might be amdvlk issue, remove amdvlk and use mesa

**Comment by zortax** [comment]
this should be fixed on zed main branch (so probably next release)

**Comment by vikigenius** [comment]
> this should be fixed on zed main branch (so probably next release)

I still have this happen in 0.224.9 which only released 6 hours ago

Looking at the way their release works I am guessing it should be fixed in 0.225

**Comment by schembriaiden** [comment]
> I still have this happen in 0.224.9 which only released 6 hours ago
> 
> Looking at the way their release works I am guessing it should be fixed in 0.225

As you correctly said its fixed from 0.225.0 onwards

**Comment by cetra3** [comment]
@zortax does that wgpu fix just reinitialize the surface if it's "out of date" ?  I.e, the underlying bug is still there in the driver, but it's handled correctly now in zed?

**Comment by zortax** [comment]
@cetra3 yes, the new zed version will just correctly handle the out-of-date surface, which wgpu correctly reports (unlike blade). You may still wanna fix this in Niri (there will be other apps that do not correctly handle this), but just so you know: this also happens on other compositors (e.g. hyprland) occasionally, albeit not as much as with niri.

**Comment by cetra3** [comment]
Ok, it's amazing to me that this works fine on gnome, but maybe it's very deep seeded

**Comment by WERDXZ** [comment]
What is your amd vulkan driver?

From what I've seen it's a AMDVLK related issue and using the Mesa driver will fix it.

**Comment by zortax** [comment]
@WERDXZ this is about Nvidia, not AMD. It may happen on AMD too, but most people complaining here are on Nvidia, because on smithay+current Nvidia, it always happens.

**Comment by WERDXZ** [comment]
I also have a nvidia card, I'll investigate into it

**Comment by zortax** [comment]
@WERDXZ you don't have to investigate, everyone already knows what the issue is :)

**Comment by Viruzaum** [comment]
zed released an update that removed blade in favor of wgpu, can you confirm if this is still an issue?

**Comment by vikigenius** [comment]
I can confirm that the issue has been solved for me.

Compositor: Niri
Zed Version: 0.225.10

**Comment by GGORG0** [comment]
Hi, so after [updating to v0.225.12](https://github.com/zed-industries/zed/compare/v0.225.10...v0.225.12) the issue is back, although in a slightly different fashion - now Zed doesn't go past the first frame at all, no matter if I resize it or not.

Started Zed and resized horizontally to fullscreen:

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/2c7e3d97-7923-4174-9751-72b9e2fad30a" />

**Comment by vikigenius** [comment]
Yup the latest update to v0.225.12 broke Zed completely again

**Comment by mgabor3141** [comment]
And v0.225.13 seems to have fixed it.

https://github.com/zed-industries/zed/issues/50734#issuecomment-3999538823

**Comment by cetra3** [comment]
OK this is working in the newer versions of zed (I'm running `Zed 0.226.4`).  Obviously there is still an outstanding issue with `blade` but I think I'm happy to close this one off
