### ISSUE TITLE
Handle matching monitor model + make + serial

### ISSUE THREAD

**Issue by YaLTeR** [YaLTeR/niri#734]
They can match, in fact the entire EDID can match between multiple monitors. Currently this can cause crashes related to workspaces moving to their original output, and probably other weirdness.

I've heard that KDE handles this by resorting to connector names when there are matching EDIDs. We need something similar I guess.

**Comment by kchibisov** [comment]
I think it doesn't really matter since it's just a _hash_, so whatever the value is is irrelevant, it's just uniquely identifies it. To compare you still would go through the EDID+serial+make+whatever.

I'm not saying to rely on connector_id, I'm saying to use it for internal operations where it doesn't matter and what matters is _uniqueness_ of the value. For all the _settings stuff_ you'd still use the `EDID+make+serial` pretty much, though via reverse mappings.

**Comment by YaLTeR** [comment]
In this case it does conflict though:
* You want to use make + model + serial for original output and not the connector name to handle the thunderbolt dock case
* But doing that breaks the logic when there are two monitors with exactly matching EDID + make + model + serial where you can only use the connector name

So in case where there are multiple monitors with exactly matching EDID + make + model + serial, these matching monitors should switch to connector names, as a workaround.

**Comment by kchibisov** [comment]
I'm not sure what you're talking about in a thunderbolt dock case, the name of the connector is irrelevant and user configuration is based on the edid/etc where you reverse map it to connector_id.

Like the issue with dock creating a new name doesn't matter, since you use u64 from id, since it's a unique value for the given monitor, for user config you have e.g. `Vec<(u64, EDID)>` where you search stuff to apply.

The only issue would be that you apply the same configuration twice if monitors exactly match, but probably could have more random data pulled.

**Comment by YaLTeR** [comment]
Added a workaround debug flag until there's a proper fix:
```
debug {
    disable-monitor-names
}
```

**Comment by myned** [comment]
To add some context, this also seems to occur when multiple connectors are enabled from the same monitor, fixed by either the `disable-monitor-names` flag or disabling the output entirely (I do this anyways as I use the iGPU for desktop and dGPU for passthrough to a VM).

**Comment by YaLTeR** [comment]
Hmm, do you mean like plugging in the same monitor by both HDMI and DP and enabling both? Or plugging in a monitor that needs two connectors at once?

**Comment by Myned** [comment]
The same monitor plugged via DP into the iGPU and HDMI into the dGPU, both enabled.

`niri msg outputs`
```
Output "Samsung Electric Company S34CG50 HNBW401587" (DP-1)
  Current mode: 3440x1440 @ 100.000 Hz
  Variable refresh rate: supported, disabled
  Physical size: 800x340 mm
  Logical position: 0, 0
  Logical size: 3440x1440
  Scale: 1
  Transform: normal
  Available modes:
    3440x1440@59.973 (preferred)
    3440x1440@100.000 (current)
    ...

Output "Samsung Electric Company S34CG50 HNBW401587" (HDMI-A-3)
  Disabled
  Variable refresh rate: supported, disabled
  Physical size: 800x340 mm
  Available modes:
    3440x1440@59.973 (preferred)
    3440x1440@100.000
    ...
```

Enabling HDMI-A-3 results in a crash without `disable-monitor-names`.

**Comment by YaLTeR** [comment]
I pushed dca0364f4c4893b2e062f643105869ec16f71f89 which should automatically unname a newly connected monitor if a collision is detected, preventing the crash even without `disable-monitor-names`. @Myned do you mind testing that niri does not crash now even without the debug flag?

**Comment by Myned** [comment]
Unfortunately, it still crashes @ dca0364.

Not quite sure if this verifies the exact commit I built at with `niri msg version` being unknown, but `realpath $(which niri)` points to `/nix/store/kdmsb085lpp66v920mnjx5djmqqb85ki-niri-dca0364/bin/niri`.

<details>
<summary>Log with both enabled</summary>

```
Jan 04 11:34:53 hostname systemd[109175]: Starting A scrollable-tiling Wayland compositor...
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.710376Z  WARN niri: running as a session but DISPLAY is set, removing it
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.710410Z  INFO niri: starting version 0.1.10 (unknown commit)
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.721227Z DEBUG niri_config: loaded config from "/home/username/.config/niri/config.kdl"
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.760671Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD128"
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.773250Z DEBUG niri::backend::tty: device added: 57857 "/dev/dri/card1"
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.861263Z DEBUG niri::backend::tty: this is the primary node
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.861278Z DEBUG niri::backend::tty: this is the primary render node
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.892101Z DEBUG niri::backend::tty: device changed: 57857
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.931620Z DEBUG niri::backend::tty: new connector: DP-1 "Samsung Electric Company S34CG50 HNBW401587"
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.931639Z DEBUG niri::backend::tty: connecting connector: DP-1
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.931647Z DEBUG niri::backend::tty: picking mode: Mode { name: "3440x1440", clock: 533160, size: (3440, 1440), hsync: (3488, 3520, 3600), vsync: (1443, 1453, 1481), hskew: 0, vscan: 0, vrefresh: 100, mode_type: ModeTypeFlags(DRIVER) }
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.931663Z DEBUG niri::backend::tty: set max bpc to 8
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.934245Z DEBUG niri::niri: putting output DP-1 at x=0 y=0
Jan 04 11:34:53 hostname niri[154214]: 2025-01-04T17:34:53.934278Z DEBUG niri::backend::tty: device added: 57856 "/dev/dri/card0"
Jan 04 11:34:54 hostname niri[154214]: 2025-01-04T17:34:54.037603Z DEBUG niri::backend::tty: device changed: 57856
Jan 04 11:34:54 hostname niri[154214]: 2025-01-04T17:34:54.039114Z DEBUG niri::backend::tty: new connector: HDMI-A-3 "Samsung Electric Company S34CG50 HNBW401587"
Jan 04 11:34:54 hostname niri[154214]: 2025-01-04T17:34:54.039124Z DEBUG niri::backend::tty: connecting connector: HDMI-A-3
Jan 04 11:34:54 hostname niri[154214]: 2025-01-04T17:34:54.039133Z DEBUG niri::backend::tty: picking mode: Mode { name: "3440x1440", clock: 319750, size: (3440, 1440), hsync: (3488, 3520, 3600), vsync: (1443, 1453, 1481), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
Jan 04 11:34:54 hostname niri[154214]: 2025-01-04T17:34:54.039148Z DEBUG niri::backend::tty: set max bpc to 8
Jan 04 11:34:54 hostname niri[154214]: 2025-01-04T17:34:54.065599Z DEBUG niri::niri: putting output HDMI-A-3 at x=3440 y=0
Jan 04 11:34:54 hostname niri[154214]: 2025-01-04T17:34:54.065654Z  INFO niri: listening on Wayland socket: wayland-1
Jan 04 11:34:54 hostname niri[154214]: 2025-01-04T17:34:54.065658Z  INFO niri: IPC listening on: /run/user/1000/niri.wayland-1.154214.sock
Jan 04 11:34:54 hostname systemd[109175]: Started A scrollable-tiling Wayland compositor.
Jan 04 11:34:54 hostname niri[154214]: thread 'main' panicked at src/layout/monitor.rs:958:34:
Jan 04 11:34:54 hostname niri[154214]: index out of bounds: the len is 0 but the index is 0
Jan 04 11:34:54 hostname niri[154214]: stack backtrace:
Jan 04 11:34:54 hostname niri[154214]:    0: rust_begin_unwind
Jan 04 11:34:54 hostname niri[154214]:    1: core::panicking::panic_fmt
Jan 04 11:34:54 hostname niri[154214]:    2: core::panicking::panic_bounds_check
Jan 04 11:34:54 hostname niri[154214]:    3: niri::niri::State::update_keyboard_focus
Jan 04 11:34:54 hostname niri[154214]:    4: niri::niri::State::refresh_and_flush_clients
Jan 04 11:34:54 hostname niri[154214]:    5: calloop::loop_logic::EventLoop<Data>::run
Jan 04 11:34:54 hostname niri[154214]:    6: niri::main
Jan 04 11:34:54 hostname niri[154214]: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Jan 04 11:34:54 hostname systemd[109175]: niri.service: Main process exited, code=exited, status=101/n/a
Jan 04 11:34:54 hostname systemd[109175]: niri.service: Failed with result 'exit-code'.
Jan 04 11:34:54 hostname systemd[109175]: niri.service: Consumed 443ms CPU time, 159.8M memory peak.
```
</details>

<details>
<summary>Log with HDMI disabled</summary>

```
Jan 04 11:30:05 hostname systemd[55839]: Starting A scrollable-tiling Wayland compositor...
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.455709Z  WARN niri: running as a session but DISPLAY is set, removing it
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.455744Z  INFO niri: starting version 0.1.10 (unknown commit)
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.469234Z DEBUG niri_config: loaded config from "/home/username/.config/niri/config.kdl"
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.507737Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD128"
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.519999Z DEBUG niri::backend::tty: device added: 57856 "/dev/dri/card0"
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.616567Z DEBUG niri::backend::tty: device changed: 57856
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.618187Z DEBUG niri::backend::tty: new connector: HDMI-A-3 "Samsung Electric Company S34CG50 HNBW401587"
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.618220Z DEBUG niri::backend::tty: device added: 57857 "/dev/dri/card1"
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.683035Z DEBUG niri::backend::tty: this is the primary node
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.683045Z DEBUG niri::backend::tty: this is the primary render node
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.738488Z DEBUG niri::backend::tty: device changed: 57857
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.777661Z DEBUG niri::backend::tty: new connector: DP-1 "Samsung Electric Company S34CG50 HNBW401587"
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.777674Z DEBUG niri::backend::tty: connecting connector: DP-1
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.777683Z DEBUG niri::backend::tty: picking mode: Mode { name: "3440x1440", clock: 533160, size: (3440, 1440), hsync: (3488, 3520, 3600), vsync: (1443, 1453, 1481), hskew: 0, vscan: 0, vrefresh: 100, mode_type: ModeTypeFlags(DRIVER) }
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.777697Z DEBUG niri::backend::tty: set max bpc to 8
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.780325Z DEBUG niri::niri: putting output DP-1 at x=0 y=0
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.780398Z  INFO niri: listening on Wayland socket: wayland-1
Jan 04 11:30:05 hostname niri[104601]: 2025-01-04T17:30:05.780401Z  INFO niri: IPC listening on: /run/user/1000/niri.wayland-1.104601.sock
Jan 04 11:30:05 hostname systemd[55839]: Started A scrollable-tiling Wayland compositor.
Jan 04 11:33:47 hostname systemd[55839]: Stopping A scrollable-tiling Wayland compositor...
Jan 04 11:33:47 hostname systemd[55839]: Stopped A scrollable-tiling Wayland compositor.
Jan 04 11:33:47 hostname systemd[55839]: niri.service: Consumed 42.853s CPU time, 387.5M memory peak.
```
</details>

<details>
<summary>Log with disable-monitor-names and both enabled</summary>

```
Jan 04 11:38:13 hostname systemd[109175]: Starting A scrollable-tiling Wayland compositor...
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.683378Z  WARN niri: running as a session but DISPLAY is set, removing it
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.683396Z  INFO niri: starting version 0.1.10 (unknown commit)
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.690960Z DEBUG niri_config: loaded config from "/home/username/.config/niri/config.kdl"
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.732824Z  INFO niri::backend::tty: using as the render node: "/dev/dri/renderD128"
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.746533Z DEBUG niri::backend::tty: device added: 57857 "/dev/dri/card1"
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.831477Z DEBUG niri::backend::tty: this is the primary node
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.831494Z DEBUG niri::backend::tty: this is the primary render node
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.861937Z DEBUG niri::backend::tty: device changed: 57857
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.900182Z DEBUG niri::backend::tty: new connector: DP-1 "Samsung Electric Company S34CG50 HNBW401587"
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.900204Z DEBUG niri::backend::tty: connecting connector: DP-1
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.900223Z DEBUG niri::backend::tty: picking mode: Mode { name: "3440x1440", clock: 533160, size: (3440, 1440), hsync: (3488, 3520, 3600), vsync: (1443, 1453, 1481), hskew: 0, vscan: 0, vrefresh: 100, mode_type: ModeTypeFlags(DRIVER) }
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.900250Z DEBUG niri::backend::tty: set max bpc to 8
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.903598Z DEBUG niri::niri: putting output DP-1 at x=0 y=0
Jan 04 11:38:13 hostname niri[202159]: 2025-01-04T17:38:13.903642Z DEBUG niri::backend::tty: device added: 57856 "/dev/dri/card0"
Jan 04 11:38:14 hostname niri[202159]: 2025-01-04T17:38:14.001063Z DEBUG niri::backend::tty: device changed: 57856
Jan 04 11:38:14 hostname niri[202159]: 2025-01-04T17:38:14.002640Z DEBUG niri::backend::tty: new connector: HDMI-A-3 "Samsung Electric Company S34CG50 HNBW401587"
Jan 04 11:38:14 hostname niri[202159]: 2025-01-04T17:38:14.002651Z DEBUG niri::backend::tty: connecting connector: HDMI-A-3
Jan 04 11:38:14 hostname niri[202159]: 2025-01-04T17:38:14.002658Z DEBUG niri::backend::tty: picking mode: Mode { name: "3440x1440", clock: 319750, size: (3440, 1440), hsync: (3488, 3520, 3600), vsync: (1443, 1453, 1481), hskew: 0, vscan: 0, vrefresh: 60, mode_type: ModeTypeFlags(PREFERRED | DRIVER) }
Jan 04 11:38:14 hostname niri[202159]: 2025-01-04T17:38:14.002685Z DEBUG niri::backend::tty: set max bpc to 8
Jan 04 11:38:14 hostname niri[202159]: 2025-01-04T17:38:14.028703Z DEBUG niri::niri: putting output HDMI-A-3 at x=3440 y=0
Jan 04 11:38:14 hostname niri[202159]: 2025-01-04T17:38:14.028758Z  INFO niri: listening on Wayland socket: wayland-1
Jan 04 11:38:14 hostname niri[202159]: 2025-01-04T17:38:14.028762Z  INFO niri: IPC listening on: /run/user/1000/niri.wayland-1.202159.sock
Jan 04 11:38:14 hostname systemd[109175]: Started A scrollable-tiling Wayland compositor.
Jan 04 11:48:18 hostname niri[202159]: libinput error: event3  - Razer Razer Viper Ultimate Dongle: client bug: event processing lagging behind by 27ms, your system is too slow
Jan 04 11:49:44 hostname niri[202159]: libinput error: event3  - Razer Razer Viper Ultimate Dongle: client bug: event processing lagging behind by 22ms, your system is too slow
Jan 04 11:53:06 hostname systemd[109175]: Stopping A scrollable-tiling Wayland compositor...
Jan 04 11:53:07 hostname systemd[109175]: Stopped A scrollable-tiling Wayland compositor.
```
</details>

**Comment by YaLTeR** [comment]
Ah, it's on a different device. Right. Let me fix this

**Comment by YaLTeR** [comment]
Ok, please try 098c826095cf985c541194498adf9ac6552d46ec, should be working now hopefully.

**Comment by Myned** [comment]
Seems to be working without the debug flag now, thank you.

```
Output "Samsung Electric Company S34CG50 HNBW401587" (HDMI-A-3)
  Current mode: 3440x1440 @ 59.973 Hz (preferred)
  ...

Output "Unknown Unknown Unknown" (DP-1)
  Current mode: 3440x1440 @ 100.000 Hz
  ...
```

**Comment by YaLTeR** [comment]
Thanks for testing!
